# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'JieBanApp' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!

  # Pods for JieBanApp
  pod 'AFNetworking','3.1.0'
  pod 'GTMBase64'
  pod 'RegexKitLite'
  pod 'SDWebImage'
  pod 'SVPullToRefresh'
  pod 'ReactiveCocoa','2.5'
  pod 'Bugly'
  pod 'AMapSearch'
  pod 'SSZipArchive'
  pod 'DateTools'
  pod 'MJRefresh'
  pod 'SVProgressHUD'
  pod 'Masonry'
  pod 'SGQRCode', '~> 3.0.1'
  pod 'WCDB','1.0.7.5'
  pod 'SDWebImage/GIF'
  pod 'YuntxIMLib', '5.5.1'
  pod 'YYModel'
  pod 'KVOController'
  pod 'PFAudioLib'
  pod 'FSCalendar'
  pod 'UINavigation-SXFixSpace'
  pod 'UITableView+FDTemplateLayoutCell'
  pod 'AMapFoundation'
  pod 'FLAnimatedImage'
  pod 'FMDB'
  pod 'SQLiteRepairKit'

end
